### ISSUE TITLE
add `argsIgnorePattern` option

### ISSUE THREAD

**Issue by erwinmombay** [greggman/eslint-plugin-google-camelcase#3]
can we add a "argsIgnorePattern" option like the `no-unused-vars` rule. We'd like to have a prefix that the  rule can skip over.

http://eslint.org/docs/rules/no-unused-vars.html

**Comment by greggman** [comment]
Just a suggestion but you could just clone this, rename it `erwinmombay-camelcase` and add whatever features you want.  That's what I did for a project where I needed something different. Example:

https://github.com/greggman/HappyFunTimes/blob/master/dev/rules/hft-camelcase.js

**Comment by erwinmombay** [comment]
@greggman sgtm
